import { FileJson, FileText, FileSpreadsheet, FileType2, Printer } from 'lucide-react'
import { useRuntime } from '@/runtime/useRuntime'
import { Card, Button, PageHeader, IconTile } from '@/components/ui'
import { exportJson, exportCsv, buildSubmission } from '@/lib/exporters'
import { exportPdf } from '@/lib/pdf'
import { toast } from '@/store/useToast'

export default function Outputs() {
  const rt = useRuntime()
  const payload = buildSubmission(rt.form, rt.answers)
  const downloadPdf = () => {
    exportPdf({ form: rt.form, answers: rt.answers, rating: rt.rating, formulaValues: rt.formulaValues, isHidden: rt.isHidden })
    toast('PDF generated')
  }

  return (
    <div>
      <PageHeader
        eyebrow="Runtime"
        title="Outputs & Export"
        subtitle="Generate machine- and human-readable outputs from the captured answers and rated result."
      />

      <div className="mb-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <IconTile icon={FileJson} tone="green" title="JSON" subtitle="Structured submission payload" onClick={() => exportJson(rt.form, rt.answers)} />
        <IconTile icon={FileText} tone="red" title="PDF" subtitle="Field-mapped document" onClick={downloadPdf} />
        <IconTile icon={FileSpreadsheet} tone="navy" title="Excel / CSV" subtitle="Tabular answer export" onClick={() => exportCsv(rt.form, rt.answers)} />
        <IconTile icon={FileType2} tone="blue" title="Word" subtitle="Document template merge" onClick={() => window.print()} />
      </div>

      <div className="grid gap-5 lg:grid-cols-2">
        <Card className="overflow-hidden">
          <div className="flex items-center justify-between border-b border-slate-100 px-5 py-3">
            <h3 className="text-sm font-semibold text-slate-900">JSON Preview</h3>
            <div className="flex gap-2">
              <Button size="sm" variant="subtle" icon={FileJson} onClick={() => exportJson(rt.form, rt.answers)}>
                Download
              </Button>
            </div>
          </div>
          <pre className="max-h-[460px] overflow-auto bg-slate-900 p-4 text-xs leading-relaxed text-slate-100">
            {JSON.stringify(payload, null, 2)}
          </pre>
        </Card>

        <Card className="overflow-hidden">
          <div className="flex items-center justify-between border-b border-slate-100 px-5 py-3">
            <h3 className="text-sm font-semibold text-slate-900">Document Preview</h3>
            <Button size="sm" variant="subtle" icon={Printer} onClick={() => window.print()}>
              Print
            </Button>
          </div>
          <div className="p-6">
            <div className="mx-auto max-w-md rounded-lg border border-slate-200 p-6 shadow-sm">
              <div className="mb-4 flex items-center justify-between border-b border-slate-100 pb-3">
                <div>
                  <div className="text-sm font-bold text-navy-800">{rt.form.name}</div>
                  <div className="text-[11px] text-slate-400">
                    {rt.form.product} · v{rt.form.version}
                  </div>
                </div>
                <div className="text-right">
                  <div className="text-[10px] uppercase text-slate-400">Premium</div>
                  <div className="text-lg font-bold text-navy-800">
                    ${rt.rating.premium.toLocaleString()}
                  </div>
                </div>
              </div>
              <dl className="space-y-1.5 text-xs">
                {rt.visibleSections
                  .flatMap((s) => s.fields)
                  .filter((f) => f.type !== 'grid' && f.type !== 'divider' && f.type !== 'label' && rt.answers[f.apiName])
                  .slice(0, 10)
                  .map((f) => (
                    <div key={f.id} className="flex justify-between gap-4">
                      <dt className="text-slate-400">{f.label}</dt>
                      <dd className="font-medium text-slate-700">{String(rt.answers[f.apiName])}</dd>
                    </div>
                  ))}
              </dl>
              <div className="mt-4 border-t border-slate-100 pt-3 text-[10px] text-slate-400">
                Tier {rt.rating.tier} · {rt.rating.eligibility} · Generated by VENUSPRO
              </div>
            </div>
          </div>
        </Card>
      </div>
    </div>
  )
}
